/**
 * Shared seed template data for lab test result templates.
 * Used by both run-migration-0007.ts and provision-tenant.ts.
 */

export interface TemplateParam {
  parameter_name: string;
  nis_limit: string;
  unit?: string;
  parameter_group: string;
  sequence_order: number;
  data_type: string;
  spec_min?: number;
  spec_max?: number;
}

export interface TemplateData {
  name: string;
  nis_standard: string;
  nis_standard_ref: string;
  parameters: TemplateParam[];
}

export function getSeedTemplates(): TemplateData[] {
  return [
    {
      name: "Borehole Water",
      nis_standard: "NIS-554-2015",
      nis_standard_ref: "NIS 554:2015",
      parameters: [
        // Physical Tests
        {
          parameter_name: "pH",
          nis_limit: "6.5 - 8.5",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 1,
          data_type: "numerical",
          spec_min: 6.5,
          spec_max: 8.5,
        },
        {
          parameter_name: "Colour",
          nis_limit: "≤ 15 TCU",
          unit: "TCU",
          parameter_group: "Physical Tests",
          sequence_order: 2,
          data_type: "numerical",
          spec_max: 15,
        },
        {
          parameter_name: "Turbidity",
          nis_limit: "≤ 5 NTU",
          unit: "NTU",
          parameter_group: "Physical Tests",
          sequence_order: 3,
          data_type: "numerical",
          spec_max: 5,
        },
        {
          parameter_name: "Total Dissolved Solids",
          nis_limit: "≤ 500 mg/L",
          unit: "mg/L",
          parameter_group: "Physical Tests",
          sequence_order: 4,
          data_type: "numerical",
          spec_max: 500,
        },
        {
          parameter_name: "Conductivity",
          nis_limit: "≤ 1000 µS/cm",
          unit: "µS/cm",
          parameter_group: "Physical Tests",
          sequence_order: 5,
          data_type: "numerical",
          spec_max: 1000,
        },
        {
          parameter_name: "Temperature",
          nis_limit: "Ambient",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 6,
          data_type: "qualitative",
        },
        {
          parameter_name: "Odour",
          nis_limit: "Unobjectionable",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 7,
          data_type: "qualitative",
        },
        {
          parameter_name: "Taste",
          nis_limit: "Unobjectionable",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 8,
          data_type: "qualitative",
        },
        // Chemical Tests
        {
          parameter_name: "Total Hardness",
          nis_limit: "≤ 150 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 9,
          data_type: "numerical",
          spec_max: 150,
        },
        {
          parameter_name: "Calcium",
          nis_limit: "≤ 75 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 10,
          data_type: "numerical",
          spec_max: 75,
        },
        {
          parameter_name: "Magnesium",
          nis_limit: "≤ 50 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 11,
          data_type: "numerical",
          spec_max: 50,
        },
        {
          parameter_name: "Iron",
          nis_limit: "≤ 0.3 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 12,
          data_type: "numerical",
          spec_max: 0.3,
        },
        {
          parameter_name: "Manganese",
          nis_limit: "≤ 0.1 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 13,
          data_type: "numerical",
          spec_max: 0.1,
        },
        {
          parameter_name: "Chloride",
          nis_limit: "≤ 250 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 14,
          data_type: "numerical",
          spec_max: 250,
        },
        {
          parameter_name: "Sulphate",
          nis_limit: "≤ 250 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 15,
          data_type: "numerical",
          spec_max: 250,
        },
        {
          parameter_name: "Nitrate",
          nis_limit: "≤ 50 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 16,
          data_type: "numerical",
          spec_max: 50,
        },
        {
          parameter_name: "Fluoride",
          nis_limit: "≤ 1.5 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 17,
          data_type: "numerical",
          spec_max: 1.5,
        },
        {
          parameter_name: "Sodium",
          nis_limit: "≤ 200 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 18,
          data_type: "numerical",
          spec_max: 200,
        },
        {
          parameter_name: "Potassium",
          nis_limit: "≤ 12 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 19,
          data_type: "numerical",
          spec_max: 12,
        },
        {
          parameter_name: "Zinc",
          nis_limit: "≤ 3 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 20,
          data_type: "numerical",
          spec_max: 3,
        },
        {
          parameter_name: "Copper",
          nis_limit: "≤ 1 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 21,
          data_type: "numerical",
          spec_max: 1,
        },
        {
          parameter_name: "Aluminium",
          nis_limit: "≤ 0.2 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 22,
          data_type: "numerical",
          spec_max: 0.2,
        },
        {
          parameter_name: "Residual Chlorine",
          nis_limit: "0.2 - 0.5 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 23,
          data_type: "numerical",
          spec_min: 0.2,
          spec_max: 0.5,
        },
        // Microbiological Tests
        {
          parameter_name: "Total Coliform",
          nis_limit: "Absent/100mL",
          unit: "CFU/100mL",
          parameter_group: "Microbiological Tests",
          sequence_order: 24,
          data_type: "pass_fail",
        },
        {
          parameter_name: "E. coli",
          nis_limit: "Absent/100mL",
          unit: "CFU/100mL",
          parameter_group: "Microbiological Tests",
          sequence_order: 25,
          data_type: "pass_fail",
        },
        {
          parameter_name: "Heterotrophic Plate Count",
          nis_limit: "≤ 100 CFU/mL",
          unit: "CFU/mL",
          parameter_group: "Microbiological Tests",
          sequence_order: 26,
          data_type: "numerical",
          spec_max: 100,
        },
      ],
    },
    {
      name: "Bottled Water",
      nis_standard: "NIS-587-2015",
      nis_standard_ref: "NIS 587:2015",
      parameters: [
        // Physical Tests
        {
          parameter_name: "pH",
          nis_limit: "6.5 - 8.5",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 1,
          data_type: "numerical",
          spec_min: 6.5,
          spec_max: 8.5,
        },
        {
          parameter_name: "Colour",
          nis_limit: "≤ 5 TCU",
          unit: "TCU",
          parameter_group: "Physical Tests",
          sequence_order: 2,
          data_type: "numerical",
          spec_max: 5,
        },
        {
          parameter_name: "Turbidity",
          nis_limit: "≤ 1 NTU",
          unit: "NTU",
          parameter_group: "Physical Tests",
          sequence_order: 3,
          data_type: "numerical",
          spec_max: 1,
        },
        {
          parameter_name: "Total Dissolved Solids",
          nis_limit: "≤ 500 mg/L",
          unit: "mg/L",
          parameter_group: "Physical Tests",
          sequence_order: 4,
          data_type: "numerical",
          spec_max: 500,
        },
        {
          parameter_name: "Conductivity",
          nis_limit: "≤ 1000 µS/cm",
          unit: "µS/cm",
          parameter_group: "Physical Tests",
          sequence_order: 5,
          data_type: "numerical",
          spec_max: 1000,
        },
        {
          parameter_name: "Odour",
          nis_limit: "Odourless",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 6,
          data_type: "qualitative",
        },
        {
          parameter_name: "Taste",
          nis_limit: "Tasteless",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 7,
          data_type: "qualitative",
        },
        // Chemical Tests
        {
          parameter_name: "Total Hardness",
          nis_limit: "≤ 150 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 8,
          data_type: "numerical",
          spec_max: 150,
        },
        {
          parameter_name: "Calcium",
          nis_limit: "≤ 75 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 9,
          data_type: "numerical",
          spec_max: 75,
        },
        {
          parameter_name: "Magnesium",
          nis_limit: "≤ 50 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 10,
          data_type: "numerical",
          spec_max: 50,
        },
        {
          parameter_name: "Iron",
          nis_limit: "≤ 0.2 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 11,
          data_type: "numerical",
          spec_max: 0.2,
        },
        {
          parameter_name: "Manganese",
          nis_limit: "≤ 0.05 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 12,
          data_type: "numerical",
          spec_max: 0.05,
        },
        {
          parameter_name: "Chloride",
          nis_limit: "≤ 250 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 13,
          data_type: "numerical",
          spec_max: 250,
        },
        {
          parameter_name: "Sulphate",
          nis_limit: "≤ 250 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 14,
          data_type: "numerical",
          spec_max: 250,
        },
        {
          parameter_name: "Nitrate",
          nis_limit: "≤ 50 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 15,
          data_type: "numerical",
          spec_max: 50,
        },
        {
          parameter_name: "Fluoride",
          nis_limit: "≤ 1.5 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 16,
          data_type: "numerical",
          spec_max: 1.5,
        },
        {
          parameter_name: "Sodium",
          nis_limit: "≤ 200 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 17,
          data_type: "numerical",
          spec_max: 200,
        },
        {
          parameter_name: "Arsenic",
          nis_limit: "≤ 0.01 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 18,
          data_type: "numerical",
          spec_max: 0.01,
        },
        {
          parameter_name: "Lead",
          nis_limit: "≤ 0.01 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 19,
          data_type: "numerical",
          spec_max: 0.01,
        },
        {
          parameter_name: "Mercury",
          nis_limit: "≤ 0.001 mg/L",
          unit: "mg/L",
          parameter_group: "Chemical Tests",
          sequence_order: 20,
          data_type: "numerical",
          spec_max: 0.001,
        },
        // Microbiological Tests
        {
          parameter_name: "Total Coliform",
          nis_limit: "Absent/100mL",
          unit: "CFU/100mL",
          parameter_group: "Microbiological Tests",
          sequence_order: 21,
          data_type: "pass_fail",
        },
        {
          parameter_name: "E. coli",
          nis_limit: "Absent/100mL",
          unit: "CFU/100mL",
          parameter_group: "Microbiological Tests",
          sequence_order: 22,
          data_type: "pass_fail",
        },
        {
          parameter_name: "Heterotrophic Plate Count",
          nis_limit: "≤ 100 CFU/mL",
          unit: "CFU/mL",
          parameter_group: "Microbiological Tests",
          sequence_order: 23,
          data_type: "numerical",
          spec_max: 100,
        },
        {
          parameter_name: "Pseudomonas aeruginosa",
          nis_limit: "Absent/100mL",
          unit: "CFU/100mL",
          parameter_group: "Microbiological Tests",
          sequence_order: 24,
          data_type: "pass_fail",
        },
      ],
    },
    {
      name: "Coconut Oil",
      nis_standard: "NIS-314-2016",
      nis_standard_ref: "NIS 314:2016",
      parameters: [
        // Physical Tests
        {
          parameter_name: "Appearance",
          nis_limit: "Clear, colourless to pale yellow liquid",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 1,
          data_type: "qualitative",
        },
        {
          parameter_name: "Colour (Lovibond)",
          nis_limit: "≤ 3.0 Yellow",
          unit: "Lovibond",
          parameter_group: "Physical Tests",
          sequence_order: 2,
          data_type: "qualitative",
        },
        {
          parameter_name: "Odour",
          nis_limit: "Characteristic coconut odour",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 3,
          data_type: "qualitative",
        },
        {
          parameter_name: "Relative Density (25°C/25°C)",
          nis_limit: "0.908 - 0.921",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 4,
          data_type: "numerical",
          spec_min: 0.908,
          spec_max: 0.921,
        },
        {
          parameter_name: "Refractive Index (40°C)",
          nis_limit: "1.448 - 1.450",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 5,
          data_type: "numerical",
          spec_min: 1.448,
          spec_max: 1.45,
        },
        {
          parameter_name: "Moisture and Volatile Matter",
          nis_limit: "≤ 0.2%",
          unit: "%",
          parameter_group: "Physical Tests",
          sequence_order: 6,
          data_type: "numerical",
          spec_max: 0.2,
        },
        {
          parameter_name: "Insoluble Impurities",
          nis_limit: "≤ 0.05%",
          unit: "%",
          parameter_group: "Physical Tests",
          sequence_order: 7,
          data_type: "numerical",
          spec_max: 0.05,
        },
        // Chemical Tests
        {
          parameter_name: "Free Fatty Acids (as Lauric)",
          nis_limit: "≤ 0.5%",
          unit: "%",
          parameter_group: "Chemical Tests",
          sequence_order: 8,
          data_type: "numerical",
          spec_max: 0.5,
        },
        {
          parameter_name: "Saponification Value",
          nis_limit: "248 - 265 mg KOH/g",
          unit: "mg KOH/g",
          parameter_group: "Chemical Tests",
          sequence_order: 9,
          data_type: "numerical",
          spec_min: 248,
          spec_max: 265,
        },
        {
          parameter_name: "Iodine Value",
          nis_limit: "6.3 - 10.6 g I₂/100g",
          unit: "g I₂/100g",
          parameter_group: "Chemical Tests",
          sequence_order: 10,
          data_type: "numerical",
          spec_min: 6.3,
          spec_max: 10.6,
        },
        {
          parameter_name: "Peroxide Value",
          nis_limit: "≤ 10 meq/kg",
          unit: "meq/kg",
          parameter_group: "Chemical Tests",
          sequence_order: 11,
          data_type: "numerical",
          spec_max: 10,
        },
        {
          parameter_name: "Unsaponifiable Matter",
          nis_limit: "≤ 0.8%",
          unit: "%",
          parameter_group: "Chemical Tests",
          sequence_order: 12,
          data_type: "numerical",
          spec_max: 0.8,
        },
        {
          parameter_name: "Acid Value",
          nis_limit: "≤ 1.0 mg KOH/g",
          unit: "mg KOH/g",
          parameter_group: "Chemical Tests",
          sequence_order: 13,
          data_type: "numerical",
          spec_max: 1.0,
        },
      ],
    },
    {
      name: "Groundnut Oil",
      nis_standard: "NIS-55-2016",
      nis_standard_ref: "NIS 55:2016",
      parameters: [
        // Physical Tests
        {
          parameter_name: "Appearance",
          nis_limit: "Clear, bright yellow to amber liquid",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 1,
          data_type: "qualitative",
        },
        {
          parameter_name: 'Colour (Lovibond 5.25")',
          nis_limit: "≤ 35 Yellow, ≤ 3.5 Red",
          unit: "Lovibond",
          parameter_group: "Physical Tests",
          sequence_order: 2,
          data_type: "qualitative",
        },
        {
          parameter_name: "Odour",
          nis_limit: "Characteristic groundnut odour",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 3,
          data_type: "qualitative",
        },
        {
          parameter_name: "Relative Density (25°C/25°C)",
          nis_limit: "0.912 - 0.920",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 4,
          data_type: "numerical",
          spec_min: 0.912,
          spec_max: 0.92,
        },
        {
          parameter_name: "Refractive Index (40°C)",
          nis_limit: "1.460 - 1.465",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 5,
          data_type: "numerical",
          spec_min: 1.46,
          spec_max: 1.465,
        },
        {
          parameter_name: "Moisture and Volatile Matter",
          nis_limit: "≤ 0.2%",
          unit: "%",
          parameter_group: "Physical Tests",
          sequence_order: 6,
          data_type: "numerical",
          spec_max: 0.2,
        },
        {
          parameter_name: "Insoluble Impurities",
          nis_limit: "≤ 0.05%",
          unit: "%",
          parameter_group: "Physical Tests",
          sequence_order: 7,
          data_type: "numerical",
          spec_max: 0.05,
        },
        // Chemical Tests
        {
          parameter_name: "Free Fatty Acids (as Oleic)",
          nis_limit: "≤ 0.5%",
          unit: "%",
          parameter_group: "Chemical Tests",
          sequence_order: 8,
          data_type: "numerical",
          spec_max: 0.5,
        },
        {
          parameter_name: "Saponification Value",
          nis_limit: "188 - 196 mg KOH/g",
          unit: "mg KOH/g",
          parameter_group: "Chemical Tests",
          sequence_order: 9,
          data_type: "numerical",
          spec_min: 188,
          spec_max: 196,
        },
        {
          parameter_name: "Iodine Value",
          nis_limit: "80 - 106 g I₂/100g",
          unit: "g I₂/100g",
          parameter_group: "Chemical Tests",
          sequence_order: 10,
          data_type: "numerical",
          spec_min: 80,
          spec_max: 106,
        },
        {
          parameter_name: "Peroxide Value",
          nis_limit: "≤ 10 meq/kg",
          unit: "meq/kg",
          parameter_group: "Chemical Tests",
          sequence_order: 11,
          data_type: "numerical",
          spec_max: 10,
        },
        {
          parameter_name: "Unsaponifiable Matter",
          nis_limit: "≤ 1.0%",
          unit: "%",
          parameter_group: "Chemical Tests",
          sequence_order: 12,
          data_type: "numerical",
          spec_max: 1.0,
        },
        {
          parameter_name: "Acid Value",
          nis_limit: "≤ 1.0 mg KOH/g",
          unit: "mg KOH/g",
          parameter_group: "Chemical Tests",
          sequence_order: 13,
          data_type: "numerical",
          spec_max: 1.0,
        },
      ],
    },
    {
      name: "Sugar",
      nis_standard: "NIS-120-2016",
      nis_standard_ref: "NIS 120:2016",
      parameters: [
        // Physical Tests
        {
          parameter_name: "Appearance",
          nis_limit: "White, dry, free-flowing crystals",
          unit: "",
          parameter_group: "Physical Tests",
          sequence_order: 1,
          data_type: "qualitative",
        },
        {
          parameter_name: "Colour (ICUMSA)",
          nis_limit: "≤ 45 IU",
          unit: "IU",
          parameter_group: "Physical Tests",
          sequence_order: 2,
          data_type: "numerical",
          spec_max: 45,
        },
        {
          parameter_name: "Moisture",
          nis_limit: "≤ 0.06%",
          unit: "%",
          parameter_group: "Physical Tests",
          sequence_order: 3,
          data_type: "numerical",
          spec_max: 0.06,
        },
        {
          parameter_name: "Polarisation",
          nis_limit: "≥ 99.7°Z",
          unit: "°Z",
          parameter_group: "Physical Tests",
          sequence_order: 4,
          data_type: "numerical",
          spec_min: 99.7,
        },
        // Chemical Tests
        {
          parameter_name: "Ash Content (Conductivity)",
          nis_limit: "≤ 0.04%",
          unit: "%",
          parameter_group: "Chemical Tests",
          sequence_order: 5,
          data_type: "numerical",
          spec_max: 0.04,
        },
        {
          parameter_name: "Reducing Sugars",
          nis_limit: "≤ 0.04%",
          unit: "%",
          parameter_group: "Chemical Tests",
          sequence_order: 6,
          data_type: "numerical",
          spec_max: 0.04,
        },
        {
          parameter_name: "Sulphur Dioxide (SO₂)",
          nis_limit: "≤ 20 mg/kg",
          unit: "mg/kg",
          parameter_group: "Chemical Tests",
          sequence_order: 7,
          data_type: "numerical",
          spec_max: 20,
        },
        {
          parameter_name: "Arsenic",
          nis_limit: "≤ 1 mg/kg",
          unit: "mg/kg",
          parameter_group: "Chemical Tests",
          sequence_order: 8,
          data_type: "numerical",
          spec_max: 1,
        },
        {
          parameter_name: "Lead",
          nis_limit: "≤ 2 mg/kg",
          unit: "mg/kg",
          parameter_group: "Chemical Tests",
          sequence_order: 9,
          data_type: "numerical",
          spec_max: 2,
        },
        {
          parameter_name: "Copper",
          nis_limit: "≤ 2 mg/kg",
          unit: "mg/kg",
          parameter_group: "Chemical Tests",
          sequence_order: 10,
          data_type: "numerical",
          spec_max: 2,
        },
      ],
    },
  ];
}
